controller_frequency: 30.0                 #z在move_base文件里面设置，在这基本可以忽略
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.3
   min_vel_x: 0.05
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   min_in_place_vel_theta: 0.2
   max_vel_theta: 1.0 
   min_vel_theta: -1.0 
   escape_vel: -0.1
   acc_lim_x: 0.5
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 0.5

   holonomic_robot: false
   yaw_goal_tolerance: 0.4      # about 6 degrees
   xy_goal_tolerance: 0.2       # 10 cm
   latch_xy_goal_tolerance: false           #if locked(true),robot just adjust the orientation when it reachs to the goal
   pdist_scale: 0.6
   gdist_scale: 0.8
   meter_scoring: true

   heading_lookahead: 0.6       #原地旋转向前看的距离
   heading_scoring: false       #computing the distance by orientation（false） or by path
   heading_scoring_timestep: 0.9       #沿着模拟轨迹向前看的时间
   occdist_scale: 0.8      #控制器应该避开障碍物的的轻易程度，默认0.1
   oscillation_reset_dist: 0.05        #在振荡标志被清零前，机器人必须在出行多远。默认0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.7             #模拟轨迹的时间，默认1.0s
   sim_granularity: 0.025         #给定轨迹的步长，默认0.025米
   angular_sim_granularity: 0.025                #给定角度轨迹的弧长，默认0.025弧度
   vx_samples: 6                              #x方向速度的样本数，默认为8
   vy_samples: 0                           # zero for a differential drive robot
   vtheta_samples: 20            #角速度的样本数，默认为20
   dwa: false                     #是否使用动态窗口方法（DWA），或者是否使用轨迹。默认为true
   simple_attractor: false
