global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0   # 0.5  5.0
  static_map: true
  publish_frequency: 0.5   # 0
  rolling_window: false  # 如果static_map设置为true，此处必须是false
  transform_tolerance: 0.5    # 1.0  坐标系间的转换语序最大延时
  map_type: costmap
  resolution: 0.05
  width: 30
  height: 30
  origin_x: -50.0
  origin_y: -50.0
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
